#!/bin/bash
yum install -y httpd
yum install -y mysql-server mysql-common mysql-client
/etc/init.d/mysqld start
mysqladmin -u root password 'root'
cd /opt/codedeploy-agent/deployment-root/
pwd
cd `ls -ltr | tail -1 | tr -s ' ' | cut -d ' ' -f 9`
pwd
cd `ls -ltr | tail -1 | tr -s ' ' | cut -d ' ' -f 9`
pwd
cp -R deployment-archive/* /usr/share/tomcat6/webapps/
mysql -uroot -proot < /usr/share/tomcat6/webapps/db.sql
